---
description: Editor, Project Member, and Projecr Designer
date: December 14, 2024
format: html
---

**<span style="color: #2596be;">"Halloweekend in Claremont: A Documentarian Analysis of 5C Party Promo Culture"</span>** is a documentary that was produced as a group project for my Anthropology of Digital Cultures class. Beginning development in October 2024, 2 of my classmates and I conducted ethnographic research centering the cresting racial, administrative, and political tensions, both internal and external to Pomona College, and their effects on how on-campus parties are promoted, and, more importantly, how the promoters and attendees interact (or don't) with one another. 

```{=html}

  <div style="text-align: center;">
    <video width="640" height="360" controls>
      <source src="/docs/Anthro.mp4" type="video/mp4">
      Your browser does not support the video tag.
    </video>
  </div>

```

This short documentary gives a brief, intimate peek into the parties thrown throughout Halloweekend 2024 (Oct 31 - Nov 2). Examining music, design, communication pipelines, and administrative changes at Pomona since the 90's, we designed this project to include the documentary below and a complementary ethnographic research paper. 

I edited this in it's entirety, and filmed about a third of the content; the aesthetics are intentionally unpolished, shaky, and unclear to emulate the chaos and instability reflected both in a night out and emerging political tensions in Claremont. The low quality, however, is for file processing reasons to display on this site (apologies for the 480p!). 

