project:
  type: website
  output-dir: docs
  
website:
  title: "- jazz :)"
  navbar:
    right:
      - text: "(!about me!)"
        href: about.qmd
        
      - text: "professional work"
        menu:
         - text: "overview"
           href: overview.qmd
         - text: "current resume"
           href: resume.qmd
         - text: "past activities"
           href: pastacts.qmd
         - text: "organizations"
           href: orgs.qmd
           
      - text: "projects"
        menu:
         - text: "The Loop"
           href: TheLoop.qmd
         - text: "Hi-De-Ho: Honoring Cab Calloway through Animation"
           href: Hi-De-Ho.qmd
         - text: "Halloweekend in Claremont"
           href: Halloweekend.qmd
         - text: "Cowboy Poker"
           href: poker.qmd
         - text: "Tech Accountability Archive"
           href: TAA.qmd
           
      - text: "creative works"
        menu:
          - text: "poems & creative writing"
            href: writing.qmd
          - text: "essays"
            href: essays.qmd
          - text: "photography"
            href: photos.qmd
        
      - text: "Data Viz"
        menu:
          - text: "Dataset 1"
            href: Database1.qmd
          - text: "Dataset 2"
            href: Database2.qmd
          - text: "String Analysis"
            href: StringAnalysis.qmd
            
      - text: "contact me!"
        href: contact.qmd
        
        
  page-footer: 
    left: "Jazzmin (jazz) Pearl Duncan"

format:
  html:
    css: styles.css
    toc: true
    page-layout: full


