project:
  type: website
  output-dir: docs
  
website:
  title: "best, jazz"
  navbar:
    right:
      - text: "(!click me!)"
        href: about.qmd
      - text: "resumé"
        menu:
         - text: "current resume"
           href: resume.qmd
      - text: "projects"
        menu:
         - text: "The Loop"
           href: TheLoop.qmd
         - text: "Hi-De-Ho: Honoring Cab Calloway through Animation"
           href: Hi-De-Ho.qmd
         - text: "Halloweekend in Claremont"
           href: Halloweekend.qmd
         - text: "Cowboy Poker"
         - text: "Tech Accountability Archive"

           
      - text: "misc creations"
        menu:
          - text: "organizations"
          - text: "poems & creative writing"
          - text: "essays"
          - text: "photography"

      - text: "contact me!"
        menu:
          - text: "Personal Instagram"
            href: https://www.instagram.com/jazzmiinpearll/
          - text: "Email"
            href: "mailto:jpduncan2022@gmail.com?&subject=I Came From Your Website!"
          - text: GitHub Repo
            href: https://github.com/jazzminpearlduncan/Website-Project.git
format:
  html:
    theme:
      - cerulean
    css: docs/styles.css
    toc: true
    page-layout: full


