project:
  type: website
  output-dir: docs
  
website:
  title: "- jazz :)"
  navbar:
    right:
      - text: "(!click me!)"
        href: about.qmd
      - text: "professional work"
        menu:
         - text: "overview"
           href: professionalwork/overview.qmd
         - text: "current resume"
           href: professionalwork/resume.qmd
         - text: "past activities"
           href: professionalwork/pastacts.qmd
         - text: "organizations"
           href: professionalwork/orgs.qmd
      - text: "projects"
        menu:
         - text: "The Loop"
           href: projects/TheLoop.qmd
         - text: "Hi-De-Ho: Honoring Cab Calloway through Animation"
           href: projects/Hi-De-Ho.qmd
         - text: "Halloweekend in Claremont"
           href: projects/Halloweekend.qmd
         - text: "Cowboy Poker"
           href: projects/poker.qmd
         - text: "Tech Accountability Archive"
           href: projects/TAA.qmd

           
      - text: "creative works"
        menu:
          - text: "poems & creative writing"
            href: creativework/writing.qmd
          - text: "essays"
            href: creativework/essays.qmd
          - text: "photography"
            href: creativework/photos.qmd
      - text: "contact me!"
        href: contact.qmd

            
format:
  html:
    css: docs/styles.css
    toc: true
    page-layout: full


