project:
  type: website
  output-dir: docs
  
website:
  title: "- jazz :)"
  navbar:
    right:
      - text: "(!about me!)"
        href: about.qmd
           
      - text: "projects"
        menu:
         - text: "The Loop (Print Production)"
           href: TheLoop.qmd
         - text: "Hi-De-Ho: Honoring Cab Calloway throughout Media History"
           href: Hi-De-Ho.qmd
         - text: "Halloweekend in Claremont Documentary"
           href: Halloweekend.qmd
         - text: "Cowboy Poker Shoot"
           href: poker.qmd
         - text: "Tech Accountability Archive"
           href: TAA.qmd
           
      - text: "other works"
        menu:
          - text: "essays"
            href: essays.qmd
          - text: "poems & creative writing (under construction)"
          - text: "photography (under construction)"

      - text: "Data Viz"
        menu:
          - text: "Dataset 1"
            href: Database1.qmd
          - text: "Dataset 2"
            href: Database2.qmd
          - text: "String Analysis"
            href: StringAnalysis.qmd
            
      - text: "contact me!"
        href: contact.qmd
        
        
  page-footer: 
    left: "Jazzmin (jazz) Pearl Duncan"

format:
  html:
    css: styles.css
    toc: true
    page-layout: full


