---
format: html
---

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/17CicZDKMQxTyo6wXS02Xz?utm_source=generator" width="100%" height="100" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

### about me

My name is Jazzmin, or Jazz, and I am currently a Junior at Pomona College studying Media Studies and Data Science, with a concentration in Electronic Media. I've bounced around several different interest areas -- including (but not limited to) AI, Intellectual Property Law, DJing, and News Writing -- and have found that Data Science and Media Studies perfectly capture my undying interest in the *transfer of information*. 

Data transfers, radio signals, news casts, remixed tracks; it's all information that's been diced up to appeal to or be understood by different subjects. This concept, that everything we process (including media) is just re-purposed data, is not new; however, it has underpinned my extracurricular and professional pursuits.

I love to experiment with boundary-stressing avenues of both data and cultural expressions, particularly through writing, music, and video editing. Chopping and screwing visual, sonic, numerical, textual, and historical data, I aim to broach the world of entertainment journalists; bridging my creative ability to tell complex stories with my passion for the dissemination of information through high-impact, culturally relevant work. 

### about my work

I have been writing as a journalist for 6 years; producing audio-visual content (documentary film, fan-edits, music, etc.) for 3 years; and managing several coinciding cross-disciplinary projects for 2 years. From *The Knight Times Newspaper* to *The Post Newspaper of Galveston County* to *The Feedbacker*, I've maintained a pointed interest in pop-culture developments and entertainment news, varying between print and visual media as mediums for storytelling through my reporting. Starting Circuits, Internet, Media, + Software (CIMS), my on-campus production organization, has been my boldest step in embracing this vision of a multi-media, interdisciplinary work environment. 

Publishing *The Loop* -- a Zine collection dedicated to dignifying and platforming student artwork, writing, software, and interactive media projects -- under CIMS, as well as maintaining scheduled community engagement and education events, is one of my proudest achievements, skill- and concept-wise; one that I am looking forward to expanding upon professionally. 

Embracing music, film, and writing as chosen mediums, I am looking to pursue a career in entertainment journalism, music A&R, or creative content development where I can continue to hold my hand to the pulse of pop-culture, challenge arbitrary boundaries, advocate for underrepresented voices, platform important conversations, and investigate how people and information interact with one another.


### about my interests (hyperfixations)

In my free time, I play The Sims (either 2 or 3); my total time played now totals ~4700 hours! If I'm not doing that, I'm probably mastering audio for a DJ set, writing poetry, or simply doing classwork. 

If you're curious, my top 4 movies (on Letterboxd) are as follows: *The Wiz (1978)*, *Zola*, *Blackkklansman*, and *A.I. Artificial Intelligence*.
(Honorable Mentions: *The Princess and The Frog*, *Tales from the Hood*, *Django Unchained*) 

Current hyperfixation blurb: I am currently experimenting with music production and animation tools; and I am absolutley enamored by the process of mastering audio, then building a given storyline off of the music, documenting what and how I *see* and *feel* when listening to music. I'm deeply fascinated by the process of generating narrative value through sound, which is embedded with a wealth of cultural knowledge. 

I also am entranced by *timelines* in media; how cultural artifacts progress, change, and build upon themselves over time, especially music, performance, and film.

