---
title: "Runtime through The Years"
description: Bar graph analysis of movie runtime over time
author: Jazzmin Duncan
date: February 17, 2025
format: html
---


```{r, echo=FALSE}
library(dplyr)
library(readr)

summer_movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-07-30/summer_movies.csv')

important_movies <- summer_movies |>
  mutate(years = year) |>
  select(years, runtime_minutes, average_rating) |>
  filter(years>1945, !is.na(years), !is.na(runtime_minutes), !is.na(average_rating)) 
  

important_movies
```

```{r, fig.width=10, fig.height=8, echo=FALSE}
library(ggplot2)
ggplot(data=important_movies, aes(x = years, y = runtime_minutes, color = average_rating)) +
  geom_point() +
  labs(
    title = "Changes in Movie Runtime (1945-2024)",
       x = "Year",
       y = "Runtime (min)")
colnames(summer_movies)

  
```

TidyTuesday dataset: https://github.com/rfordatascience/tidytuesday/tree/a95bcce0d7e09590519ba1ff98512fbf10f443af/data/2024/2024-07-30

Data origins: The Internet Movie Database collected this data; it contains a list of movies with the name "Summer" in the title.