---
title: "Hi-De-Ho"
description: Honoring Cab Calloway, the Rotoscope, and Media History
author: Jazzmin Duncan
date: February 17, 2025
format: html
---

:::: {.content-visible when-format="html"}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/7wf7NTTnSbWVkvDChqKFup?utm_source=generator" width="100%" height="100" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
::::
<span style="background-color: yellow; font-weight: bold;">^^^listen to Icon - Jaden Smith to hear this sampled!</span>

This is an ongoing project, planned to be completed in early March, focusing on a specific clip from a Betty Boop cartoon featuring a rotoscoped animation of a ghost dancing. The original footage, traced over to create the animation, was a performance of "Minnie the Moocher" by Cab Calloway and his Cotton Club Band—an influential group that played a role in laying the conceptual groundwork for MoTown and Black Hollywood’s rise to prominence throughout the 20th century. 

While the animated version has become an iconic artifact, even evolving into a meme, it has overshadowed its source material, simultaneously preserving and erasing history. This project will explore how animation can both immortalize and obscure cultural contributions, examining the interplay between adaptation and historical visibility. The final product will be a few-minute-long animated short that traces key moments in animation and music history, incorporating stylistic recreations, backtracking, and archival references.

The short will feature clipped performances from Cab Calloway, the Nicholas Brothers, Janet Jackson, and other, more contemporary musicians; as well as references to key moments in culture, specifically from the perspective of a young adult who was raised on music videos (me).

