---
title: "hello!"
image: https://media.licdn.com/dms/image/v2/D5603AQGHsSaLa6h51A/profile-displayphoto-shrink_400_400/B56ZTxjuReGUAg-/0/1739219461919?e=1746057600&v=beta&t=opAPXylC0pYJIDxqyRBSHpeJrI95RTTTHjTf5tiisK8
toc: false
about:
  template: solana
  image-width: 10em
  image-shape: rounded
  links:
    - text: Instagram
      href: https://www.instagram.com/5circuitsmedia/
    - text: Email
      href: "jazzyp12.love@gmail.com"
    - text: GitHub Repo
      href: https://github.com/jazzminpearlduncan/Website-Project.git
      
    
        
---
Although this site only contains classwork now, I hope to further develop it as a landing page for my art portfolio, contains poetry, documentaries, digital art, and motion pictures, along with my more pride-inducing research papers, and perhaps, even a resume. 

A preview of my poetry: 
act i: just what’s a wiz?, i’ll know soon as i get home (thoughts of an unemployed junior)
and just what’s a wiz? 
what would i ask him?
i look around me and see oz,
walls full of graffiti and beautiful people
but what’s in me?
don’t know what i’m made of
my brain is rotting out of my head and taking any vision of the future with it
walk? you can’t walk.
but i know i can, but where am i going?
i am the turkey and i am blowing out my own flame.
i am the crow. trash! t-rash!
my mind collapses in on itself as i read every cover letter i write, application i submit, and writing sample i provide
and so i lay back and **** that ****, and **** a glass of *** 
i can’t win, who am i competing against?
the crow, haters? the wiz, fraud? my conscience, the invisible?
the lines between reality and a demoralizing oz have become blurred by brainrot and repetitive fanaticism from ya novels
the results of the first experiment, subject is a hopeless failure. you’re not you’re just the product of negative thinking. first we gotta get rid of these crows. 
you got it, clyde!
i’m on my way to find the wiz, he’s gonna get me back home.
i’m looking for where i end and the crows begin

Thanks for reading! The line breaks are a bit messed up because of formtting.

I really enjoyed this project and look forward to learning ore, nd experimenting with Quarto sites!


