---
title: "The Loop"
format: html
execute: 
  echo: false
---

:::: {.content-visible when-format="html"}
<iframe style="border-radius:12px" 
  src="https://open.spotify.com/embed/track/1xUhr8hmAdA8mF6VDJ3M1q" 
  width="100%" height="100" frameborder="0" 
  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture">
</iframe>
::::


The Loop is a product of the collective work of students across the 5 Claremont Colleges. Created by Circuits, Internet, Media, and Software, The Loop has published one issue, and the second is currently in progress! [Submit here! We don't discriminate!](https://docs.google.com/forms/d/e/1FAIpQLSdFZAVr6rLbzUoZ9l7t2vkuqzaIL1vBYVQ-xS4xFCwb8WEQ7w/viewform?usp=header) As the Founder, I am incredibly proud of the momentum, content, and community this magazine has fostered in such a short amount of time, allowing me and my peers to grow as both artists, organizers, and multimedia fanatics. 

I independently curated and edited each submission, designed each page, and led print distribution with stringent time constraints. This magazine was primarily meant to be humanitarian, platforming and dignifying student works that would otherwise be forever stuck in their files; however, it has developed into a more mature, formalized production as the organization behind it - CIMS, founded by me as well – has grown due to my persistent scouting of new E-Board members, student works, and potential events. 

This experience has prepared me to report on, organize, and advise people and ideas, especially those related to media, technology, and culture. Having to collaborate extensively across a wide variety of academic disciplines has allowed me to gain the necessary experience to begin learning the ropes of doing so professionally. 


```{=html}
<object data="projects/Loop.pdf" type="application/pdf" width="100%" height="50%" style="min-height:100vh;">
    <p>It appears you don't have a PDF plugin for this browser.
    No biggie... you can <a href="projects/Loop.pdf">click here to
    download the PDF file.</a></p>
</object>
```